name: VI Analyzer Tests

on:
  pull_request:
    paths:
      - '**/*.vi'

jobs:
  run-vi-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Authenticate to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull Docker Image from GHCR
        run: docker pull ghcr.io/shivacode-2/lv2025linux:latest

      - name: Run VI Analyzer Tests
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          ghcr.io/shivacode-2/lv2025linux:latest \
          bash -c "xvfb-run -a -s \"-screen 0 1024x768x24\" LabVIEWCLI -LogToConsole true -OperationName RunVIAnalyzer -ConfigPath '/workspace/Test VIs/VIAnalyzerCfgFile.viancfg' -ReportPath '/usr/local/natinst/ContainerExamples/Results.txt' -LabVIEWPath '/usr/local/natinst/LabVIEW-2025-64/labviewprofull'"

